const CONTRIBUTION_FORM_SCOPE = [
  'form#editForm',
  'form#edit-book-form',
  'form#edit-route-form',
  'form#flag-content-form',
  'form.edit-form',
  'form.improvement-form',
  'form[action^="/improvement/"]',
  'form[action*="mountainproject.com/improvement/"]',
  'form[action$="/bad-name-report"]',
  'form[action*="/add/photo"]',
  'form[action*="/edit/imageLink/"]',
  'form[action*="/upload/start/trail"]',
  'form[action*="/edit/book/"]',
  '.improvement-modal',
  '[id*="improvement-modal"]',
].join(', ');

const CONTRIBUTION_ACTION_SCOPE = [
  '.improve-page-general',
  'a[href^="/add/"]',
  'a[href^="/edit/"]',
  'a[href^="/suggest/"]',
  'a[href^="/improvement/"]',
  'a[href^="/updates/"]',
  'a[href^="/upload/"]',
  'a[href^="/area/"][href*="/add/photo"]',
  'a[href^="/route/"][href*="/add/photo"]',
  'a[href*="mountainproject.com/add/"]',
  'a[href*="mountainproject.com/edit/"]',
  'a[href*="mountainproject.com/suggest/"]',
  'a[href*="mountainproject.com/improvement/"]',
  'a[href*="mountainproject.com/updates/"]',
  'a[href*="mountainproject.com/upload/"]',
  'a[href*="mountainproject.com/area/"][href*="/add/photo"]',
  'a[href*="mountainproject.com/route/"][href*="/add/photo"]',
].join(', ');

const CONTRIBUTION_OVERLAY_SCOPE = [
  '#login-modal',
  '#access-gate',
  '#share-content-modal',
  '.share-content-modal',
  '#global-modal',
  '#data-confirm-modal',
  '#flag-content-modal',
  '#flag-content-form',
].join(', ');

const CONTRIBUTION_FAQ_SCOPE = '#global-modal-body #help-page .faq';

export const CONTRIBUTION_SELECTORS = {
  scope: [
    CONTRIBUTION_FORM_SCOPE,
    CONTRIBUTION_ACTION_SCOPE,
    CONTRIBUTION_OVERLAY_SCOPE,
  ].join(', '),
  actionScope: CONTRIBUTION_ACTION_SCOPE,
  overlayScope: CONTRIBUTION_OVERLAY_SCOPE,
  faqScope: CONTRIBUTION_FAQ_SCOPE,
  form: [
    CONTRIBUTION_FORM_SCOPE,
  ].join(', '),
  helperText: [
    'form.edit-form p',
    'form.edit-form .text-muted',
    'form.edit-form .text-danger',
    'form.edit-form .form-char-count',
    'form.improvement-form p',
    'form.improvement-form .text-muted',
    'form.improvement-form .text-danger',
    'form.improvement-form .form-char-count',
    'form[action^="/improvement/"] p',
    'form[action^="/improvement/"] .text-muted',
    'form[action^="/improvement/"] .text-danger',
    'form[action^="/improvement/"] .form-char-count',
    'form[action^="/improvement/"] > .mb-2',
    'form[action^="/improvement/"] .label-left',
    'form[action^="/improvement/"] .label-right',
    'form[action^="/improvement/"] .text-nowrap',
    'form[action^="/improvement/"] #zoom-tip',
    'form[action^="/improvement/"] .strong.p-half',
    '.improvement-modal p',
    '.improvement-modal .text-muted',
    '.improvement-modal .text-danger',
    'form[action*="/add/photo"] p',
    'form[action*="/add/photo"] .help-block',
    'form[action*="/edit/imageLink/"] p',
    'form[action*="/edit/imageLink/"] .help-block',
    'form[action*="/upload/start/trail"] p',
    'form[action*="/upload/start/trail"] .help-block',
    'form[action*="/edit/book/"] p',
    'form[action*="/edit/book/"] .help-block',
    '#editForm .form-char-count',
    '.container-fluid > .text-muted',
  ].join(', '),
  uiText: [
    '#access-gate p',
    '#login-modal .all-sites-disclaimer p',
    '#login-modal .orSeparator',
    '#login-modal .g-recaptcha-response > span',
    '#share-content-modal p',
    '.share-content-modal p',
    '#global-modal-body p',
    '#global-modal-body .text-muted',
    '#global-modal-body .text-danger',
    '#global-modal-body .dropdown-header',
    '#global-modal-body li',
    `${CONTRIBUTION_FAQ_SCOPE} > h2`,
    `${CONTRIBUTION_FAQ_SCOPE} .faq-item > h3`,
    `${CONTRIBUTION_FAQ_SCOPE} .faq-item > div`,
    'form#editForm li',
    'form#editForm .text-warm',
    '.faq .faq-item > div',
    '#flag-content-form p',
    '.page-title .pt-2',
    '.pt-main-content .pt-2',
    '#edit-route-form .field-note',
    '#edit-route-form .fr-placeholder',
    '#edit-route-form .fr-counter',
    '.improve-page-general .dropdown-header',
    '.improve-page-general [role="menuitem"]',
  ].join(', '),
} as const;
