export const HELP_SELECTORS = {
  classicPage: '#help-page',
  classicTopicCard: '.faq-section-card',
  classicFaqQuestion: '#help-page .list-group-item-heading',
  classicFaqAnswer: '#help-page .list-group-item-text .faq-answer',
  hubPage: '#help-hub-page',
  hubFaqSection: '#help-hub-page .hh-faq-section',
  hubFaqQuestion: '#help-hub-page .hh-faq-qt',
  hubFaqAnswer: '#help-hub-page .hh-faq-a',
  hubResultCard: '#help-hub-page .hh-result-card',
  hubGettingStartedContent: '#help-hub-page .hh-gs-card h3, #help-hub-page .hh-gs-card p',
  hubTopicDescription: '#help-hub-page .hh-cat-card p',
  hubFeatureRequestContent: '.hh-wish-title, .hh-wish-desc',
  hubCategoryOptions: '#help-hub-page #hh-form-cat option',
  hubCategoryLabel: '#help-hub-page #hh-cat-label',
  hubCategoryFilters: '#help-hub-page .hh-cat-filter-opt',
  nameReviewPage: '#name-review-process',
  nameReviewTitle: '#name-review-process > .page-title h1',
  authoredContent: [
    '#help-page .list-group-item-heading',
    '#help-page .list-group-item-text .faq-answer',
    '#help-hub-page .hh-faq-qt',
    '#help-hub-page .hh-faq-a',
    '#help-hub-page .hh-result-card',
    '#help-hub-page .hh-gs-card h3',
    '#help-hub-page .hh-gs-card p',
    '#help-hub-page .hh-cat-card p',
    '#help-hub-page .hh-wish-title',
    '#help-hub-page .hh-wish-desc',
    '#name-review-process',
  ].join(', '),
  inlineSource: '.mpkr-inline-translation-source',
  protectedFeatureRequestData: [
    '.hh-wish-meta strong',
    '.hh-forum-author',
    '.hh-forum-text',
    '.hh-forum-avatar',
    '.hh-forum-date',
    '.hh-forum-likes',
    '.hh-vote-count',
    '.hh-s-chip .cnt',
    '#hh-char-count',
    '#help-hub-page input',
    '#help-hub-page textarea',
    '#help-hub-page [contenteditable]:not([contenteditable="false"])',
  ].join(', '),
  uiText: [
    '#help-hub-page p',
    '#help-hub-page div',
    '#help-page .faq-section-card',
    '#help-page .text-xs-center',
    '#help-page .contact-us-modal',
    '#help-hub-page .hh-header',
    '#help-hub-page .hh-tab-btn',
    '#help-hub-page .hh-chip',
    '#help-hub-page .hh-cat-card',
    '#help-hub-page .hh-faq-header',
    '#help-hub-page .hh-section-title',
    '#help-hub-page .hh-section-sub',
    '#help-hub-page .hh-footer-cta',
    '#help-hub-page .hh-s-chip',
    '#help-hub-page .hh-cat-filter-opt',
    '#help-hub-page .hh-status-badge',
    '#help-hub-page .hh-cat-badge',
    '#help-hub-page .hh-empty-state',
    '#help-hub-page .hh-modal',
    '#help-hub-page .hh-form-group',
    '#help-hub-page .hh-form-note',
    '#help-hub-page .hh-wish-actions',
    '#help-hub-page .hh-update-toggle',
    '#help-hub-page .hh-view-thread',
    '#help-hub-page .hh-results-label',
    '#help-hub-page .hh-wl-sort',
    '#help-hub-page .hh-wl-cat-btn',
    '#name-review-process > .page-title',
  ].join(', '),
} as const;

export const HELP_AUTHORED_ROOT_SELECTOR = [
  HELP_SELECTORS.classicFaqQuestion,
  HELP_SELECTORS.classicFaqAnswer,
  HELP_SELECTORS.hubFaqQuestion,
  HELP_SELECTORS.hubFaqAnswer,
  HELP_SELECTORS.hubResultCard,
  HELP_SELECTORS.hubGettingStartedContent,
  HELP_SELECTORS.hubTopicDescription,
  HELP_SELECTORS.nameReviewPage,
].join(', ');
