export const USER_SELECTORS = {
  profileRoot: '#user-profile',
  contactRoot: '#contact-user, [data-contact-user], form[action*="/contact-user"]',
  profileNavigation: '#user-profile nav, #user-profile [role="navigation"], #user-profile .nav-tabs',
  activityAction: '#user-profile .comment-table a, #user-profile .activity-action',
  contributions: '#user-profile .contributions, #user-profile [data-contributions]',
  community: '#user-profile .community, #user-profile [data-community]',
  actionCard: '#user-profile .action-card',
  protectedProfileContent: [
    '#user-profile #user-info h2',
    '#user-profile #user-info .location',
    '#user-profile #user-info .user-location',
    '#user-profile #user-info [data-user-location]',
    '#user-profile .fr-view',
    '#user-profile .comment-body',
    '#user-profile .user-content',
    '#user-profile .activity-body',
    '#user-profile .comment-table .comment-row > td > .row .col-md-12',
    '#user-profile .forum-message-table .forum-message-row > td > .mb-half > strong',
    '#user-profile .forum-message-table .forum-message-row > td > div:last-child',
    '#user-profile .photo-title',
    '#user-profile .photo-caption',
    '#user-profile a[href*="/route/"]',
    '#user-profile a[href*="/area/"]',
    '#user-profile a[href*="/photo/"]',
    '#user-profile .comment-body a[href*="/user/"]',
    '#user-profile .activity-body a[href*="/user/"]',
    '#user-profile .comment-author',
    '#user-profile .user-name',
    '#user-profile [rel="author"]',
    '.fr-view',
    '.comment-body',
    '.user-content',
    '.activity-body',
    '.forum-post-body',
    '.message-body',
    '.photo-title',
    '.photo-caption',
    'a[href*="/route/"]',
    'a[href*="/area/"]',
    '.comment-author',
    '.user-name',
    '[rel="author"]',
    '[data-user-name]',
  ].join(', '),
  protectedContactContent: [
    'a[href*="/user/"]',
    '.recipient-name',
    '.user-name',
    '[data-recipient-name]',
    '[data-user-name]',
  ].join(', '),
} as const;
