/** Fixed forum chrome. Callers must exclude authored topics, posts and user metadata. */
const FORUM_UI: Readonly<Record<string, string>> = {
  'Mountain Project Forums': 'Mountain Project 포럼',
  'Mountain Project': 'Mountain Project',
  Forums: '포럼',
  Forum: '포럼',
  Gear: '장비',
  General: '일반',
  Regional: '지역별',
  Partners: '등반 파트너',
  'FOR SALE / FOR FREE / WANT TO BUY': '판매 / 무료 나눔 / 구매 희망',
  'Climbing Gear Discussion/Reviews': '클라이밍 장비 토론 및 리뷰',
  'Climbing Gear Discussion': '클라이밍 장비 토론',
  'Climbing Gear Reviews': '클라이밍 장비 리뷰',
  'Lost and Found': '분실물 및 습득물',
  'General Climbing': '클라이밍 일반',
  'Trip Reports': '등반 여행기',
  'Beginning Climbers': '초보 클라이머',
  Bouldering: '볼더링',
  'Injuries and Accidents': '부상 및 사고',
  'Sport Climbing': '스포츠 클라이밍',
  'Trad Climbing': '전통 등반',
  'Climbing Photos & Videos': '클라이밍 사진 및 영상',
  Mountaineering: '등산 및 고산 등반',
  'Fixed Hardware: Bolts & Anchors': '고정 확보물: 볼트 및 앵커',
  'Ice Climbing': '빙벽 등반',
  'Big Wall and Aid Climbing': '거벽 및 인공 등반',
  'Rope Soloing': '로프 솔로 등반',
  'Training Forum': '훈련 포럼',
  "Women's Forum": '여성 포럼',
  Memorial: '추모',
  'Other Sports': '기타 스포츠',
  'Politics and Rock Climbing': '정치 및 암벽등반',
  'Extended Trips and International Partners': '장기 원정 및 해외 등반 파트너',
  Help: '도움말',
  'Mountain Project News': 'Mountain Project 소식',
  'Discuss MountainProject.com': 'MountainProject.com에 관한 이야기',
  'MountainProject.com - the site': 'MountainProject.com 사이트',
  'iPhone & Android App Feedback': 'iPhone 및 Android 앱 의견',
  'Dirtbag climber exchange!': '알뜰 클라이머들의 장비 거래!',
  'Open discussions regarding climbing gear.': '클라이밍 장비에 관해 자유롭게 이야기하는 공간입니다.',
  'Formal Climbing Gear Reviews': '클라이밍 장비 전문 리뷰',
  'Missing something? Found something?': '잃어버리거나 주운 물건이 있나요?',
  "Climbing-related topics that don't fit elsewhere. Non-climbing related posts go in the Politics forum!": '다른 게시판에 해당하지 않는 클라이밍 이야기를 나눠 주세요. 클라이밍과 관련 없는 글은 정치 포럼에 올려 주세요!',
  'Your stories, epics, and adventures': '여러분의 등반 이야기와 모험담',
  'Helping beginners get into the sport': '초보자의 클라이밍 입문을 돕는 공간',
  'Land of the uber-strong pad people.': '패드를 메고 다니는 힘센 볼더러들의 공간.',
  'Discuss accidents, injuries, treatments, and other health-related issues here.': '사고, 부상, 치료 및 건강에 관한 이야기를 나눠 주세요.',
  'Bolts. Yummmmmmm.': '볼트라면 언제나 환영!',
  'Bolts? What are those?': '볼트? 그게 뭐죠?',
  'Share your original content here. Discuss climbing photography and videography.': '직접 만든 콘텐츠를 공유하고 클라이밍 사진과 영상 촬영에 관해 이야기해 주세요.',
  'How to chase Marmots in the high alpine.': '높은 산에서 마멋을 찾아다니는 법.',
  'Discuss techniques, hardware, and best practices.': '기술과 장비, 권장 방법에 관해 이야기해 주세요.',
  'Icy hearts unite!': '얼음을 사랑하는 마음으로 모여요!',
  'Like to scare yourself hanging on gear? This is the place.': '장비에 매달리는 아찔함을 즐기시나요? 바로 이곳입니다.',
  'Where solitude and self-belay collide.': '혼자만의 등반과 자기 확보가 만나는 곳.',
  'Read this forum, and learn how to pump-yourself-up.': '이 포럼에서 몸과 마음을 단련하는 방법을 배워 보세요.',
  'A place for women to share experiences and discuss issues. Zero-tolerance moderation.': '여성들이 경험을 공유하고 여러 문제를 논의하는 공간입니다. 규칙 위반은 엄격하게 관리합니다.',
  "A place to remember those we've lost from our community.": '세상을 떠난 우리 클라이밍 공동체의 사람들을 기억하는 공간입니다.',
  'Bike? Ski? Kayak? Meet climbers with other interests.': '자전거, 스키, 카약도 즐기시나요? 다른 취미도 함께하는 클라이머를 만나 보세요.',
  'Issues that impact the climbing community.': '클라이밍 공동체에 영향을 미치는 문제들.',
  'All Forums': '전체 포럼',
  'Latest Posts in all Forums': '전체 포럼의 최신 글',
  'Latest Posts': '최신 글',
  'Recent Posts': '최근 글',
  'New Posts': '새 글',
  'My Posts': '내 글',
  'My Topics': '내가 작성한 글',
  'Followed Topics': '알림을 받는 글',
  'Start New Topic': '새 글 작성',
  'New Topic': '새 글',
  'Create New Topic': '새 글 작성',
  'Post New Topic': '새 글 등록',
  Topic: '주제',
  Topics: '주제',
  Title: '제목',
  'Topic Title': '글 제목',
  Subject: '제목',
  Message: '내용',
  'Your Reply': '내 답글',
  Replies: '답글',
  Views: '조회',
  'Last Post': '최근 글',
  'Last post': '최근 글',
  'Last Post:': '최근 글:',
  'Last post:': '최근 글:',
  'Original Post': '원글',
  'Post Reply': '답글 작성',
  'Add Reply': '답글 추가',
  Reply: '답글',
  Quote: '인용',
  Flag: '신고',
  'Report Post': '게시글 신고',
  'Follow topic:': '글 알림:',
  'Follow Topic': '글 알림 받기',
  'Unfollow Topic': '글 알림 해제',
  'Notify on site': '사이트에서 알림',
  Email: '이메일',
  'Email Notifications': '이메일 알림',
  'Back to Forum': '포럼으로 돌아가기',
  'Back to Forums': '포럼 목록으로 돌아가기',
  Search: '검색',
  'Show All': '전체 보기',
  Routes: '루트',
  Areas: '지역',
  Users: '사용자',
  Photos: '사진',
  'Search Forums': '포럼 검색',
  'Search Forum': '포럼 검색',
  'Search Results': '검색 결과',
  'Search Topics': '글 검색',
  'Search this forum': '이 포럼 검색',
  'Search all forums': '전체 포럼 검색',
  'Advanced Search': '상세 검색',
  'Search by keyword': '검색어로 검색',
  Filter: '필터',
  Filters: '필터',
  'Filter by': '필터 조건',
  'Sort by:': '정렬:',
  'Sort By': '정렬',
  'Sort By:': '정렬:',
  Default: '기본 순',
  Longest: '긴 순',
  Shortest: '짧은 순',
  'Last Activity': '최근 활동',
  Newest: '최신 순',
  Oldest: '오래된 순',
  Relevance: '관련도 순',
  'Most Recent': '최신 순',
  'Most Replies': '답글 많은 순',
  'All Topics': '전체 글',
  'Clear Filters': '필터 초기화',
  Apply: '적용',
  Previous: '이전',
  Next: '다음',
  First: '처음',
  Last: '마지막',
  'Previous Page': '이전 페이지',
  'Next Page': '다음 페이지',
  'First Page': '첫 페이지',
  'Last Page': '마지막 페이지',
  'Previous page': '이전 페이지',
  'Next page': '다음 페이지',
  'First page': '첫 페이지',
  'Last page': '마지막 페이지',
  'Load More': '더 불러오기',
  'Loading...': '불러오는 중...',
  'Loading…': '불러오는 중…',
  'Loading posts...': '게시글을 불러오는 중...',
  'No topics yet.': '아직 글이 없습니다.',
  'No posts yet.': '아직 게시글이 없습니다.',
  'No replies yet.': '아직 답글이 없습니다.',
  'No topics found.': '글을 찾지 못했습니다.',
  'No posts found.': '게시글을 찾지 못했습니다.',
  'No results found.': '검색 결과가 없습니다.',
  'No Results': '검색 결과 없음',
  'This topic is locked.': '이 글은 잠겨 있습니다.',
  'This topic has been deleted.': '삭제된 글입니다.',
  'Something went wrong.': '문제가 발생했습니다.',
  'Please try again.': '다시 시도해 주세요.',
  'Sign Up or Log In': '회원가입 또는 로그인',
  'Sign Up': '회원가입',
  'Log In': '로그인',
  'Log In to Reply': '로그인 후 답글 작성',
  'Please log in to reply.': '답글을 작성하려면 로그인해 주세요.',
  'You must be logged in to post a reply.': '답글을 작성하려면 로그인해야 합니다.',
  'You must be logged in to post.': '글을 작성하려면 로그인해야 합니다.',
  'Please Confirm': '확인해 주세요',
  Submit: '등록',
  Preview: '미리보기',
  Cancel: '취소',
  Close: '닫기',
  Edit: '수정',
  Delete: '삭제',
  Save: '저장',
  Required: '필수',
  Optional: '선택 사항',
  'This field is required.': '필수 입력 항목입니다.',
  'Please enter a title.': '제목을 입력해 주세요.',
  'Please enter a message.': '내용을 입력해 주세요.',
};

const FORUM_PLACEHOLDERS: Readonly<Record<string, string>> = {
  'Search forums': '포럼 검색',
  'Search Forums': '포럼 검색',
  'Search this forum': '이 포럼 검색',
  'Search all forums': '전체 포럼 검색',
  'Search topics': '글 검색',
  'Search...': '검색...',
  'Search terms': '검색어',
  'Enter keywords': '검색어 입력',
  'Topic title': '글 제목',
  'Enter a title': '제목 입력',
  'Enter a subject': '제목 입력',
  'Write a reply': '답글 작성',
  'Write your reply': '답글 작성',
  'Write your message': '내용 작성',
  'Type your message': '내용 입력',
};

export function translateForumUi(value: string): string | undefined {
  const text = value.replace(/\s+/g, ' ').trim();
  if (Object.prototype.hasOwnProperty.call(FORUM_UI, text)) return FORUM_UI[text];

  // Match metadata against the source so dates and region names retain their spelling/spacing.
  const source = value.trim();
  const lastPost = source.match(/^Last [Pp]ost:([\s\S]+)$/);
  if (lastPost) return `최근 글:${lastPost[1]}`;
  const region = source.match(/^Regional forum for ([\s\S]+)$/);
  if (region) return `${region[1]} 지역 포럼`;
  const partners = source.match(/^(.+) Partners$/);
  if (partners) return `${partners[1]} 등반 파트너`;

  const page = text.match(/^(?:Page )?([\d,]+) of ([\d,]+)$/);
  if (page) return `${page[1]} / ${page[2]} 페이지`;
  const count = text.match(/^([\d,]+) (replies|reply|topics|topic|posts|post|views|view)$/i);
  if (count) {
    const kind = count[2]!.toLowerCase();
    const label = kind.startsWith('repl') ? '답글'
      : kind.startsWith('topic') ? '주제'
        : kind.startsWith('post') ? '게시글' : '조회';
    return `${label} ${count[1]}${kind.startsWith('view') ? '회' : '개'}`;
  }
  return undefined;
}

export function translateForumPlaceholder(value: string): string | undefined {
  const text = value.replace(/\s+/g, ' ').trim();
  return Object.prototype.hasOwnProperty.call(FORUM_PLACEHOLDERS, text)
    ? FORUM_PLACEHOLDERS[text]
    : undefined;
}
