export type MountainProjectSectionCategory =
  | 'description'
  | 'access'
  | 'safety';

export const SECTION_CATEGORY_BY_HEADING: Readonly<
  Record<string, MountainProjectSectionCategory>
> = {
  Description: 'description',
  '설명': 'description',
  'Getting There': 'access',
  '가는 방법': 'access',
  Location: 'access',
  '위치': 'access',
  Protection: 'safety',
  '보호 장비': 'safety',
  Descent: 'safety',
  '하강': 'safety',
  'Travel Information': 'access',
  '여행 정보': 'access',
  'Helpful Hints': 'description',
  '유용한 팁': 'description',
  OVERVIEW: 'description',
  '개요': 'description',
  'Official Park Info': 'description',
  '공원 공식 정보': 'description',
  Weather: 'description',
  '날씨': 'description',
  Access: 'access',
  '접근 정보': 'access',
  'The Cliffs': 'description',
  '암벽 구역': 'description',
  'Climbing Gear': 'safety',
  '등반 장비': 'safety',
  'Fixed Anchors in the Gunks': 'safety',
  'The Gunks의 고정 앵커': 'safety',
  Guidebooks: 'description',
  '가이드북': 'description',
  'Where to Stay': 'access',
  '숙박 정보': 'access',
  'Where to Eat': 'access',
  '식사 정보': 'access',
  'Other Resources': 'description',
  '기타 자료': 'description',
  'Rain and Wet Rock': 'safety',
  '비와 젖은 암벽': 'safety',
  'Human Waste': 'safety',
  '배설물 처리': 'safety',
  'The Scenic Loop: Entry Fee, Reservation System, and Late Exit Passes': 'access',
  'Scenic Loop: 입장료, 예약제 및 늦은 퇴장 허가': 'access',
  'Commercial, Large Groups (>15), and Guest Permit Lottery': 'access',
  '상업 활동, 대규모 단체(15명 초과) 및 게스트 허가 추첨': 'access',
  Camping: 'access',
  '캠핑': 'access',
  'Red Rock or Rocks?': 'description',
  'Red Rock인가 Red Rocks인가?': 'description',
};

export const SECTION_TITLE_TRANSLATIONS: Readonly<Record<string, string>> = {
  Description: '설명',
  '설명': '설명',
  'Getting There': '가는 방법',
  '가는 방법': '가는 방법',
  Location: '위치',
  '위치': '위치',
  Protection: '보호 장비',
  '보호 장비': '보호 장비',
  Descent: '하강',
  '하강': '하강',
  'Travel Information': '여행 정보',
  '여행 정보': '여행 정보',
  'Helpful Hints': '유용한 팁',
  '유용한 팁': '유용한 팁',
  OVERVIEW: '개요',
  '개요': '개요',
  'Official Park Info': '공원 공식 정보',
  '공원 공식 정보': '공원 공식 정보',
  Weather: '날씨',
  '날씨': '날씨',
  Access: '접근 정보',
  '접근 정보': '접근 정보',
  'The Cliffs': '암벽 구역',
  '암벽 구역': '암벽 구역',
  'Climbing Gear': '등반 장비',
  '등반 장비': '등반 장비',
  'Fixed Anchors in the Gunks': 'The Gunks의 고정 앵커',
  'The Gunks의 고정 앵커': 'The Gunks의 고정 앵커',
  Guidebooks: '가이드북',
  '가이드북': '가이드북',
  'Where to Stay': '숙박 정보',
  '숙박 정보': '숙박 정보',
  'Where to Eat': '식사 정보',
  '식사 정보': '식사 정보',
  'Other Resources': '기타 자료',
  '기타 자료': '기타 자료',
  'Rain and Wet Rock': '비와 젖은 암벽',
  '비와 젖은 암벽': '비와 젖은 암벽',
  'Human Waste': '배설물 처리',
  '배설물 처리': '배설물 처리',
  'The Scenic Loop: Entry Fee, Reservation System, and Late Exit Passes': 'Scenic Loop: 입장료, 예약제 및 늦은 퇴장 허가',
  'Scenic Loop: 입장료, 예약제 및 늦은 퇴장 허가': 'Scenic Loop: 입장료, 예약제 및 늦은 퇴장 허가',
  'Commercial, Large Groups (>15), and Guest Permit Lottery': '상업 활동, 대규모 단체(15명 초과) 및 게스트 허가 추첨',
  '상업 활동, 대규모 단체(15명 초과) 및 게스트 허가 추첨': '상업 활동, 대규모 단체(15명 초과) 및 게스트 허가 추첨',
  Camping: '캠핑',
  '캠핑': '캠핑',
  'Red Rock or Rocks?': 'Red Rock인가 Red Rocks인가?',
  'Red Rock인가 Red Rocks인가?': 'Red Rock인가 Red Rocks인가?',
};

export const AREA_NARRATIVE_SECTION_HEADINGS: ReadonlySet<string> = new Set([
  'Description',
  '설명',
  'Getting There',
  '가는 방법',
]);

export const CLASSIC_ROUTE_SECTION_HEADING_PREFIXES: readonly string[] = [
  'Classic Climbing Routes',
  '클래식 루트',
];
